### ISSUE TITLE
01_homework

### ISSUE THREAD

**Issue by wally-wally** [web-class/Phase01_web-starter#1]
# 01_Homework

<br>

## 1. OX퀴즈(맞으면 O, 틀리면 X)

- WWW는 'World Wide Web'의 약자이다. ( )
- 현재 우리가 웹 브라우저로 보고 있는 웹은 유럽 입자 물리 연구의 팀 버너스리가 개발했다. ( )
- Javascript, HTML은 프로그래밍 언어이다. ( )
- CSS 언어로 웹 페이지에 스타일 속성을 줄 수 있다. ( )

<br>

## 2. 코드에 대한 다음 물음에 답하시오.

<img src="https://user-images.githubusercontent.com/52685250/87652327-08cb1880-c78f-11ea-8509-a4fde3a6bbae.png" width="700">

- 해당 웹 페이지를 한국어로 설정하기 위해 (a)에 들어갈 알맞은 코드를 작성하시오. - (    )
- (b)에 들어갈 해당 웹 페이지의 제목을 설정할 수 있는 태그 명을 작성하시오. - (    )
- (d)에 들어갈 웹 페이지에서 특정 영역의 머리말 영역을 의미하는 시멘틱 태그를 작성하시오. - (    )
- 맞으면 O, 틀리면 X
  - `nav` 태그와 `footer` 태그는 형제 관계이다. ( )
  - `ul` 태그와 `li` 태그는 부모-자식 관계이다. ( )
  - `article` 태그와 `li` 태그는 형제 관계이다. ( )
  - `head` 태그와 `body` 태그 사이의 영역(주석으로 표시한 (c) 영역)에 텍스트를 작성하면 웹 브라우저 상에 표시된다. ( )
  - `head` 안의 `meta` 태그는 반드시 작성하지 않아도 된다. ( )

**Comment by ICY-SIM** [comment]
1. o/ o/ x/ o
2. kr/ title/ header/ o/ o/ x/ x/ o

**Comment by wally-wally** [comment]
> 1. o/ o/ x/ o
> 2. kr/ title/ header/ o/ o/ x/ x/ o

- 아쉽지만 `kr` > `ko` 입니다ㅜ 그래도 나머지는 다 맞았어요! 수고했어요~
