### ISSUE TITLE
02_homework

### ISSUE THREAD

**Issue by wally-wally** [web-class/Phase01_web-starter#2]
# 02_Homework

<br>

## 아래 사진과 같은 `과일 목록 ` 페이지를 만드시오.

![캡처](https://user-images.githubusercontent.com/52685250/87739194-39a45f80-c81a-11ea-9b65-ca6a55e5b258.PNG)

:heavy_check_mark: <b>과제 상세 명세</b>

- `<과일 목록>` : `h1` 태그
- `과일 판매 홈페이지` : `h2` 태그
- 과일 이미지와 텍스트는 `table` 태그로 구성할 것
- 이미지 파일은  `images` 폴더 안에 있음
- 이미지 삽입시 `alt` 속성 값으로 각 과일의 이름을 작성할 것
- 과일 판매 홈페이지 리스트는 순서 없는 리스트 태그로 작성할 것
- `G마켓` 클릭하면 현재 창에서 `https://browse.gmarket.co.kr/search?keyword=과일` 주소로 이동
- `TMON` 클릭하면 새 창에서 `https://search.tmon.co.kr/search/?keyword=과일` 주소로 이동
- `마켓 월리(준비중)`은 링크가 걸려있지 않으며 취소선이 그어짐

**Comment by wally-wally** [comment]
https://web-class-homework.netlify.app/ 에서 `web-starter` > `02_homework`의 `Practice` 버튼을 클릭해서 자료 다운받아서 과제 수행

**Comment by ICY-SIM** [comment]
good
